### ISSUE TITLE
Changing Stock values directly

### ISSUE THREAD

**Issue by JaBecker** [stochsd/stochsd#157]
Is it possible to change Stock values directly inside Flows?

I would like to simulate the movement of a bouncing ball and for the reflection of the ball on the surface, the velocity has to change from [v] to -[v] in an instant. In InsightMaker, this is solved by

if [Position]<0 then [v] <- Abs([v])*[damping ratio]

**Comment by Magnus93** [comment]
The value of a Stock can only be changed using in- or out-Flows. Since the underlying simulation engine in StochSD is the same, that should still be possible.

**Comment by JaBecker** [comment]
So, how can I implement this instantaneous change in StochSD?

**Comment by JaBecker** [comment]
`if [Ort]<0 then
    [Geschwindigkeit] <- Abs([Geschwindigkeit])*[Daempfung]
    [Beschleunigung]
else
    [Beschleunigung]
end if`
